(() => {
  const airlines = [
    ["CA","CCA","Air China","中国国际航空"],["CZ","CSN","China Southern Airlines","中国南方航空"],
    ["MU","CES","China Eastern Airlines","中国东方航空"],["HU","CHH","Hainan Airlines","海南航空"],
    ["ZH","CSZ","Shenzhen Airlines","深圳航空"],["MF","CXA","XiamenAir","厦门航空"],
    ["3U","CSC","Sichuan Airlines","四川航空"],["SC","CDG","Shandong Airlines","山东航空"],
    ["HO","DKH","Juneyao Air","吉祥航空"],["9C","CQH","Spring Airlines","春秋航空"],
    ["GJ","CDC","Loong Air","长龙航空"],["JD","CBJ","Beijing Capital Airlines","首都航空"],
    ["NS","HBH","Hebei Airlines","河北航空"],["GS","GCR","Tianjin Airlines","天津航空"],
    ["QW","QDA","Qingdao Airlines","青岛航空"],["EU","UEA","Chengdu Airlines","成都航空"],
    ["KY","KNA","Kunming Airlines","昆明航空"],["8L","LKE","Lucky Air","祥鹏航空"],
    ["PN","CHB","West Air","西部航空"],["KN","CUA","China United Airlines","中国联合航空"],
    ["DR","RLH","Ruili Airlines","瑞丽航空"],["GX","CBG","GX Airlines","北部湾航空"],
    ["TV","TBA","Tibet Airlines","西藏航空"],["UQ","CUH","Urumqi Air","乌鲁木齐航空"],
    ["AQ","JYH","9 Air","九元航空"],["Y8","YZR","Suparna Airlines","金鹏航空"],
    ["OQ","CQN","Chongqing Airlines","重庆航空"],["FU","FZA","Fuzhou Airlines","福州航空"],
    ["LT","SNG","Longjiang Airlines","龙江航空"],["DZ","EPA","Donghai Airlines","东海航空"],
    ["CX","CPA","Cathay Pacific","国泰航空"],["HX","CRK","Hong Kong Airlines","香港航空"],
    ["UO","HKE","HK Express","香港快运"],["NX","AMU","Air Macau","澳门航空"],
    ["BR","EVA","EVA Air","长荣航空"],["CI","CAL","China Airlines","中华航空"],
    ["JX","SJX","STARLUX Airlines","星宇航空"],["IT","TTW","Tigerair Taiwan","台湾虎航"],
    ["AE","MDA","Mandarin Airlines","华信航空"],
    ["SQ","SIA","Singapore Airlines","新加坡航空"],["TR","TGW","Scoot","酷航"],
    ["MH","MAS","Malaysia Airlines","马来西亚航空"],["OM","MGL","MIAT Mongolian Airlines","蒙古民用航空"],["KT","HOG","Mahogany Air","Mahogany Air"],["AK","AXM","AirAsia","亚洲航空"],
    ["D7","XAX","AirAsia X","亚洲航空长途"],["OD","MXD","Batik Air Malaysia","马印航空"],
    ["GA","GIA","Garuda Indonesia","印度尼西亚鹰航"],["QZ","AWQ","Indonesia AirAsia","印尼亚洲航空"],
    ["JT","LNI","Lion Air","狮子航空"],["BI","RBA","Royal Brunei Airlines","文莱皇家航空"],
    ["TG","THA","Thai Airways","泰国国际航空"],["FD","AIQ","Thai AirAsia","泰国亚洲航空"],
    ["SL","TLM","Thai Lion Air","泰国狮航"],["VZ","TVJ","Thai VietJet Air","泰越捷航空"],
    ["VN","HVN","Vietnam Airlines","越南航空"],["VJ","VJC","VietJet Air","越捷航空"],
    ["PR","PAL","Philippine Airlines","菲律宾航空"],["5J","CEB","Cebu Pacific","宿务太平洋航空"],
    ["JL","JAL","Japan Airlines","日本航空"],["NH","ANA","All Nippon Airways","全日空"],
    ["MM","APJ","Peach Aviation","乐桃航空"],["GK","JJP","Jetstar Japan","捷星日本航空"],
    ["7G","SFJ","StarFlyer","星悦航空"],["KE","KAL","Korean Air","大韩航空"],
    ["OZ","AAR","Asiana Airlines","韩亚航空"],["LJ","JNA","Jin Air","真航空"],
    ["TW","TWB","T'way Air","德威航空"],["7C","JJA","Jeju Air","济州航空"],
    ["BX","ABL","Air Busan","釜山航空"],["ZE","ESR","Eastar Jet","易斯达航空"],
    ["AI","AIC","Air India","印度航空"],["6E","IGO","IndiGo","靛蓝航空"],
    ["UK","VTI","Vistara","塔塔新加坡航空"],["QF","QFA","Qantas","澳洲航空"],
    ["JQ","JST","Jetstar Airways","捷星航空"],["VA","VOZ","Virgin Australia","维珍澳洲航空"],
    ["NZ","ANZ","Air New Zealand","新西兰航空"],["EK","UAE","Emirates","阿联酋航空"],
    ["EY","ETD","Etihad Airways","阿提哈德航空"],["QR","QTR","Qatar Airways","卡塔尔航空"],
    ["SV","SVA","Saudia","沙特阿拉伯航空"],["WY","OMA","Oman Air","阿曼航空"],
    ["GF","GFA","Gulf Air","海湾航空"],["FZ","FDB","flydubai","迪拜航空"],
    ["TK","THY","Turkish Airlines","土耳其航空"],["VF","TKJ","AJet","AJet航空"],["LY","ELY","EL AL Israel Airlines","以色列航空"],
    ["ET","ETH","Ethiopian Airlines","埃塞俄比亚航空"],["KQ","KQA","Kenya Airways","肯尼亚航空"],
    ["MS","MSR","EgyptAir","埃及航空"],["AT","RAM","Royal Air Maroc","摩洛哥皇家航空"],
    ["SA","SAA","South African Airways","南非航空"],["BA","BAW","British Airways","英国航空"],
    ["VS","VIR","Virgin Atlantic","维珍大西洋航空"],["LH","DLH","Lufthansa","汉莎航空"],
    ["LX","SWR","SWISS","瑞士国际航空"],["OS","AUA","Austrian Airlines","奥地利航空"],
    ["AF","AFR","Air France","法国航空"],["KL","KLM","KLM Royal Dutch Airlines","荷兰皇家航空"],
    ["IB","IBE","Iberia","西班牙国家航空"],["AY","FIN","Finnair","芬兰航空"],
    ["SK","SAS","Scandinavian Airlines","北欧航空"],["LO","LOT","LOT Polish Airlines","波兰航空"],
    ["TP","TAP","TAP Air Portugal","葡萄牙航空"],["AZ","ITY","ITA Airways","意大利航空"],
    ["EI","EIN","Aer Lingus","爱尔兰航空"],["FR","RYR","Ryanair","瑞安航空"],
    ["U2","EZY","easyJet","易捷航空"],["W6","WZZ","Wizz Air","维兹航空"],
    ["VY","VLG","Vueling","伏林航空"],["DY","NOZ","Norwegian","挪威航空"],
    ["A3","AEE","Aegean Airlines","爱琴海航空"],["FI","ICE","Icelandair","冰岛航空"],
    ["UA","UAL","United Airlines","美国联合航空"],["AA","AAL","American Airlines","美国航空"],
    ["DL","DAL","Delta Air Lines","达美航空"],["WN","SWA","Southwest Airlines","西南航空"],
    ["B6","JBU","JetBlue","捷蓝航空"],["AS","ASA","Alaska Airlines","阿拉斯加航空"],
    ["NK","NKS","Spirit Airlines","精神航空"],["F9","FFT","Frontier Airlines","边疆航空"],
    ["AC","ACA","Air Canada","加拿大航空"],["WS","WJA","WestJet","西捷航空"],
    ["AM","AMX","Aeroméxico","墨西哥航空"],["LA","LAN","LATAM Airlines","南美航空"],
    ["AV","AVA","Avianca","哥伦比亚航空"],["CM","CMP","Copa Airlines","巴拿马航空"],
    ["G3","GLO","GOL Linhas Aéreas","高尔航空"],["AD","AZU","Azul Brazilian Airlines","巴西蓝色航空"]
  ].map(([iata,icao,en,zh]) => ({ iata, icao, en, zh }));

  const aircraft = {
    Airbus: ["A220-100","A220-300","A300B2/B4","A300-600","A310-200","A310-300","A318","A319","A319neo","A320","A320neo","A321","A321neo","A321LR","A321XLR","A330-200","A330-300","A330-800","A330-900","A340-200","A340-300","A340-500","A340-600","A350-900","A350-1000","A380-800"],
    Boeing: ["707-120/320","717-200","727-100","727-200","737-100","737-200","737-300","737-400","737-500","737-600","737-700","737-800","737-900ER","737-7","737-8","737-9","737-10","747-100","747-200","747-300","747-400","747-8","757-200","757-300","767-200","767-300ER","767-400ER","777-200","777-200ER","777-200LR","777-300","777-300ER","777-8","777-9","787-8","787-9","787-10"],
    COMAC: ["ARJ21-700 / C909","C919"],
    Embraer: ["ERJ 135","ERJ 140","ERJ 145","E170","E175","E190","E195","E190-E2","E195-E2"],
    Bombardier: ["CRJ100/200","CRJ700","CRJ900","CRJ1000","Dash 8 Q100/200","Dash 8 Q300","Dash 8 Q400"],
    ATR: ["ATR 42-300/500","ATR 42-600","ATR 72-200/500","ATR 72-600"],
    "McDonnell Douglas": ["DC-8","DC-9","DC-10","MD-80","MD-81","MD-82","MD-83","MD-87","MD-88","MD-90","MD-11"],
    "British Aerospace": ["BAe 146-100","BAe 146-200","BAe 146-300","Avro RJ70","Avro RJ85","Avro RJ100"],
    Fokker: ["Fokker 50","Fokker 70","Fokker 100"],
    Lockheed: ["L-1011 TriStar"],
    Tupolev: ["Tu-134","Tu-154","Tu-204"],
    Ilyushin: ["Il-62","Il-76","Il-86","Il-96"],
    Antonov: ["An-24","An-124","An-148"],
    Historic: ["Concorde","de Havilland Comet","Sud Aviation Caravelle","Vickers VC10"]
  };

  window.FLIGHT_ARCHIVE_REFERENCE = { airlines, aircraft };
})();
